exports.name = "Name is required...";
exports.formid = "Form id is required...";
exports.fieldid = "Field id is required..."; 
exports.form_key = "Form Key is required...";
exports.keyalreadyExists = "This Form key is already exists...";
exports.addedmsg = "Record added successfully";
exports.updatemsg = "Record updated successfully";
exports.errormsg = "Something went wrong!";
exports.updatefailuremsg = "Unable to Update the field's. Please try again later !"